from __future__ import annotations

import logging
from pyroller.utils.files import atomic_path

from pyroller.i18n import _
from pathlib import Path
from typing import Optional

from pyroller.domain import AlignmentLine, AlignmentResult, WriteResult
from pyroller.utils.time import format_ass_timestamp, seconds_to_centiseconds
from pyroller.writer.base import Writer

logger = logging.getLogger("pyroller.writer")


_ASS_HEADER_TEMPLATE = """[Script Info]
; {generated_by}
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,54,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,80,80,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _escape_ass_text(text: str) -> str:
    """Escape ASS control characters so literal braces and backslashes
    are not interpreted as override tags or escape sequences."""
    return text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


class ASSKaraokeWriter(Writer):
    def __init__(
        self,
        by_tag: str = "py-roller",
        tag_type: str = "kf",
        skip_structural_lines: bool = True,
        unmatched_line_duration: float = 0.6,
    ) -> None:
        self.by_tag = by_tag
        self.tag_type = tag_type
        self.skip_structural_lines = skip_structural_lines
        self.unmatched_line_duration = max(0.1, float(unmatched_line_duration))

    @property
    def backend_name(self) -> str:
        return "ass_karaoke"

    def write(self, alignment: AlignmentResult, output_path: Path) -> WriteResult:
        from pyroller.domain.validation import validate_payload
        validate_payload(alignment.to_dict(), 'alignment_result')
        output_path.parent.mkdir(parents=True, exist_ok=True)
        written_lines = 0
        with atomic_path(output_path) as temporary, temporary.open("w", encoding="utf-8") as f:
            f.write(_ASS_HEADER_TEMPLATE.format(generated_by=_("; Generated by {by_tag}").format(by_tag=self.by_tag)))
            for index, line in enumerate(alignment.lines):
                if self._should_skip_line(line):
                    continue
                start = line.start_time
                end = self._display_end_time(alignment.lines, index)
                text = self._line_to_ass_text(line)
                f.write(
                    "Dialogue: 0,{start},{end},Default,,0,0,0,,{text}\n".format(
                        start=format_ass_timestamp(start),
                        end=format_ass_timestamp(end),
                        text=text,
                    )
                )
                written_lines += 1

        logger.info(_("Wrote %d ASS karaoke lines to %s"), written_lines, output_path)
        return WriteResult(
            output_path=output_path,
            writer_backend=self.backend_name,
            metadata={
                "line_count": written_lines,
                "tag_type": self.tag_type,
                "by_tag": self.by_tag,
                "skip_structural_lines": self.skip_structural_lines,
                "unmatched_line_duration": self.unmatched_line_duration,
            },
        )

    def _line_to_ass_text(self, line: AlignmentLine) -> str:
        if not line.aligned_units:
            return _escape_ass_text(line.raw_text)
        # Old artifacts may have phonemes in `text`. Never substitute them
        # for the user's lyrics when no trustworthy display mapping exists.
        if "".join(unit.text for unit in line.aligned_units) != line.raw_text:
            return _escape_ass_text(line.raw_text)
        groups = []
        for unit in line.aligned_units:
            span = unit.metadata.get("source_text_span")
            if span is not None and groups and groups[-1][3] == span:
                groups[-1][1] = max(groups[-1][1], unit.end_time)
                groups[-1][2] += unit.text
            else:
                groups.append([unit.start_time, unit.end_time, unit.text, span])
        chunks: list[str] = []
        cursor_cs = 0
        for start, end, text, _span in groups:
            start_cs = max(cursor_cs, seconds_to_centiseconds(max(0.0, start - line.start_time)))
            end_cs = max(start_cs, seconds_to_centiseconds(max(0.0, end - line.start_time)))
            if start_cs > cursor_cs:
                chunks.append(f"{{\\k{start_cs - cursor_cs}}}")
            chunks.append(f"{{\\{self.tag_type}{end_cs - start_cs}}}{_escape_ass_text(text)}")
            cursor_cs = end_cs
        return "".join(chunks)

    def _should_skip_line(self, line: AlignmentLine) -> bool:
        return self.skip_structural_lines and self._is_structural_line(line)

    def _is_structural_line(self, line: AlignmentLine) -> bool:
        return bool(line.metadata.get("is_spacing") or line.metadata.get("is_structural") or not line.raw_text.strip())

    def _next_non_structural_start(self, lines: list[AlignmentLine], index: int) -> Optional[float]:
        for next_index in range(index + 1, len(lines)):
            candidate = lines[next_index]
            if self._should_skip_line(candidate):
                continue
            return candidate.start_time
        return None

    def _display_end_time(self, lines: list[AlignmentLine], index: int) -> float:
        line = lines[index]
        start = line.start_time
        natural_end = start

        if line.aligned_units:
            natural_end = max(natural_end, *(unit.end_time for unit in line.aligned_units))

        matched_end = line.metadata.get("matched_end_time")
        if matched_end is not None:
            try:
                natural_end = max(natural_end, float(matched_end))
            except (TypeError, ValueError):
                pass

        next_start = self._next_non_structural_start(lines, index)
        if line.end_time is not None and line.end_time > start:
            natural_end = max(natural_end, float(line.end_time))

        # Only inferred display durations may be shortened for the next line.
        if natural_end <= start and next_start is not None and next_start > start:
            guard = min(0.08, max((next_start - start) * 0.02, 0.01))
            ceiling = max(start, next_start - guard)
            natural_end = min(start + self.unmatched_line_duration, ceiling)
        elif natural_end <= start:
            natural_end = start + self.unmatched_line_duration

        if natural_end <= start:
            natural_end = start + 0.01
        return natural_end
